### ISSUE TITLE
No longer working after recent extension upgrade

### ISSUE THREAD

**Issue by virtualviolet** [scharlessantos/minimizeall#4]
Hi

Just upgraded the extension and it is no longer working on Ubuntu 18.04.

Ubuntu 18.04
Vanilla Gnome 3.28.3

**Comment by scharlessantos** [comment]
The extension was moved to gilab. https://gitlab.com/scharlessantos/minimizeall.git

Use version to shell 3.30

**Comment by virtualviolet** [comment]
Which version of the extension? I have rolled back to v11 and it is working
again.





*From:* Charles Santos Silva <notifications@github.com>
*Sent:* Sunday, January 27, 2019 2:19 PM
*To:* scharlessantos/minimizeall <minimizeall@noreply.github.com>
*Cc:* Kevin Walker <kwalker@virtualviolet.net>; Author <
author@noreply.github.com>
*Subject:* Re: [scharlessantos/minimizeall] No longer working after recent
extension upgrade (#4)



The extension was moved to gilab.
https://gitlab.com/scharlessantos/minimizeall.git

Use version to shell 3.30

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/scharlessantos/minimizeall/issues/4#issuecomment-457905436>,
or mute the thread
